[package]
name = "nesk-web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.104"
nesk = { git = "https://github.com/sanjaykenn/nesk.git", branch = "main" }
js-sys = "0.3.81"
web-sys = { version = "0.3", features = ["Window"] }
