name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Build WASM
        run: |
          wasm-pack build --target web --out-dir docs/pkg

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs